# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: Njc0YzU4YTQxZGNiN2FlOTg5ZTljZDVmNDkzYjgwZGFjMjFjMjA2ZDNlZGQ0NTQyOTY5NTAxMWJlMzYyMzhhMDlmYzY2N2RmMjA0NmFiY2Y1NDQ4NmFlMmRkYjQyNmExMTZlNTE5MDBkMTk2YjA3MjA0NzllOWUxYWU3Yzg0NGU=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: jdTest
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: system
    password: oracle
