package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JdTestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJdTestAllPropertiesEquals(JdTest expected, JdTest actual) {
        assertJdTestAutoGeneratedPropertiesEquals(expected, actual);
        assertJdTestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJdTestAllUpdatablePropertiesEquals(JdTest expected, JdTest actual) {
        assertJdTestUpdatableFieldsEquals(expected, actual);
        assertJdTestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJdTestAutoGeneratedPropertiesEquals(JdTest expected, JdTest actual) {
        assertThat(actual)
            .as("Verify JdTest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJdTestUpdatableFieldsEquals(JdTest expected, JdTest actual) {
        assertThat(actual)
            .as("Verify JdTest relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getClassification()).as("check classification").isEqualTo(expected.getClassification()))
            .satisfies(a -> assertThat(a.getNodeId()).as("check nodeId").isEqualTo(expected.getNodeId()))
            .satisfies(a -> assertThat(a.getNode()).as("check node").isEqualTo(expected.getNode()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getCodeDescription()).as("check codeDescription").isEqualTo(expected.getCodeDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJdTestUpdatableRelationshipsEquals(JdTest expected, JdTest actual) {
        assertThat(actual)
            .as("Verify JdTest relationships")
            .satisfies(a -> assertThat(a.getParent()).as("check parent").isEqualTo(expected.getParent()));
    }
}
